In [37]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

from bs4 import BeautifulSoup
import re
import json
import requests
import openpyxl
import urllib
from urllib import parse
import lxml
from sklearn.model_selection import train_test_split

from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

import time
from sklearn.preprocessing import MinMaxScaler

import import_ipynb
from Stock import Stock
import processData
import normalize

In [38]:
SS = Stock('005930')
SK = Stock('000660')
DW=Stock('049770')
SFA=Stock('056190')
GB=Stock('024110')

sa=SS.priceamount()
sk=SK.priceamount()
dw=DW.priceamount()
sf=SFA.priceamount()
gb=GB.priceamount()
sadata=SS.idxNorm()
skdata=SK.idxNorm()
dwdata=DW.idxNorm()
sfdata=SFA.idxNorm()
gbdata=GB.idxNorm()

NameError: name 'np' is not defined

In [5]:
dtrain_inputs = []
dtrain_labels = []
dtrain_inputs.append(returnInputs(sa, sadata))
dtrain_inputs.append(returnInputs(sk, skdata))
dtrain_inputs.append(returnInputs(dw, dwdata))
dtrain_inputs.append(returnInputs(sf, sfdata))
dtrain_inputs.append(returnInputs(gb, gbdata))
dtrain_inputs = np.array(dtrain_inputs)

dtrain_labels.append(returnDailyLabels(sa, sadata))
dtrain_labels.append(returnDailyLabels(sk, skdata))
dtrain_labels.append(returnDailyLabels(dw, dwdata))
dtrain_labels.append(returnDailyLabels(sf, sfdata))
dtrain_labels.append(returnDailyLabels(gb, gbdata))
dtrain_labels = np.array(dtrain_labels)
print(dtrain_labels, dtrain_labels.shape)

[[[ 5.09 ]
  [ 5.16 ]
  [ 5.13 ]
  ...
  [ 5.66 ]
  [ 5.53 ]
  [ 5.55 ]]

 [[ 8.34 ]
  [ 8.58 ]
  [ 8.61 ]
  ...
  [ 7.6  ]
  [ 7.5  ]
  [ 7.57 ]]

 [[24.75 ]
  [24.5  ]
  [24.05 ]
  ...
  [16.   ]
  [15.7  ]
  [15.6  ]]

 [[ 3.475]
  [ 3.385]
  [ 3.52 ]
  ...
  [ 3.74 ]
  [ 3.64 ]
  [ 3.53 ]]

 [[ 1.675]
  [ 1.675]
  [ 1.695]
  ...
  [ 1.   ]
  [ 0.982]
  [ 0.946]]] (5, 1147, 1)


In [6]:
wtrain_inputs = []
wtrain_labels = []
wtrain_inputs.append(returnInputs(sa, sadata))
wtrain_inputs.append(returnInputs(sk, skdata))
wtrain_inputs.append(returnInputs(dw, dwdata))
wtrain_inputs.append(returnInputs(sf, sfdata))
wtrain_inputs.append(returnInputs(gb, gbdata))
wtrain_inputs = np.array(wtrain_inputs)
wtrain_inputs = wtrain_inputs[:,:1141,:]

wtrain_labels.append(returnWeeklyLabels(sa, sadata))
wtrain_labels.append(returnWeeklyLabels(sk, skdata))
wtrain_labels.append(returnWeeklyLabels(dw, dwdata))
wtrain_labels.append(returnWeeklyLabels(sf, sfdata))
wtrain_labels.append(returnWeeklyLabels(gb, gbdata))
wtrain_labels = np.array(wtrain_labels)
wtrain_labels = wtrain_labels[:,-1,:]
print(wtrain_labels.shape, wtrain_labels)

(5, 7) [[ 5.91   5.81   5.79   5.81   5.66   5.53   5.55 ]
 [ 7.92   7.78   7.7    7.7    7.6    7.5    7.57 ]
 [16.15  16.1   16.1   16.05  16.    15.7   15.6  ]
 [ 3.77   3.78   3.83   3.835  3.74   3.64   3.53 ]
 [ 1.11   1.11   1.105  1.12   1.     0.982  0.946]]


In [7]:
mtrain_inputs = []
mtrain_labels = []
mtrain_inputs.append(returnInputs(sa, sadata))
mtrain_inputs.append(returnInputs(sk, skdata))
mtrain_inputs.append(returnInputs(dw, dwdata))
mtrain_inputs.append(returnInputs(sf, sfdata))
mtrain_inputs.append(returnInputs(gb, gbdata))
mtrain_inputs = np.array(mtrain_inputs)
mtrain_inputs = mtrain_inputs[:,:1118,:]

mtrain_labels.append(returnMonthlyLabels(sa, sadata))
mtrain_labels.append(returnMonthlyLabels(sk, skdata))
mtrain_labels.append(returnMonthlyLabels(dw, dwdata))
mtrain_labels.append(returnMonthlyLabels(sf, sfdata))
mtrain_labels.append(returnMonthlyLabels(gb, gbdata))
mtrain_labels = np.array(mtrain_labels)
mtrain_labels = mtrain_labels[:,-1,:]
print(mtrain_labels.shape, mtrain_labels)

(5, 30) [[ 6.14   6.06   6.1    6.14   6.1    6.01   6.06   6.22   6.26   6.04
   6.03   5.92   5.89   5.92   6.04   5.95   5.97   6.05   5.93   5.95
   5.95   5.86   5.8    5.91   5.81   5.79   5.81   5.66   5.53   5.55 ]
 [ 8.63   8.52   8.52   8.69   8.51   8.31   8.37   8.5    8.47   8.19
   8.1    8.1    7.89   7.88   8.15   8.11   8.23   8.18   8.02   7.84
   7.9    7.83   7.8    7.92   7.78   7.7    7.7    7.6    7.5    7.57 ]
 [13.85  13.95  14.05  14.    14.05  13.6   13.7   13.85  14.05  14.25
  14.2   14.2   14.15  14.25  14.4   14.7   14.55  14.65  14.7   14.75
  14.75  14.65  15.65  16.15  16.1   16.1   16.05  16.    15.7   15.6  ]
 [ 3.9    3.97   4.07   4.005  3.97   3.905  3.975  4.     3.935  3.885
   3.905  3.805  3.785  3.775  3.82   3.69   3.71   3.765  3.755  3.685
   3.695  3.61   3.635  3.77   3.78   3.83   3.835  3.74   3.64   3.53 ]
 [ 1.09   1.1    1.095  1.105  1.105  1.095  1.105  1.12   1.12   1.12
   1.125  1.11   1.09   1.085  1.105  1.105  1.11   1.11   

In [8]:
dmodel = Sequential([
    layers.LSTM(512, input_shape=(dtrain_inputs.shape[1],dtrain_inputs.shape[2]), return_sequences=True),
    layers.LSTM(128),
    layers.Dense(1, activation = 'relu')
])

dmodel.compile(loss='mse',optimizer='adam', metrics='mae')
dmodel.summary()
dmodel.fit(dtrain_inputs, dtrain_labels,
    epochs=10
)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 1147, 512)         1069056   
                                                                 
 lstm_1 (LSTM)               (None, 128)               328192    
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1,397,377
Trainable params: 1,397,377
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
1/1 [==============================] - 6s 6s/step - loss: 122.8327 - mae: 8.2364
Epoch 2/10
1/1 [==============================] - 2s 2s/step - loss: 77.2663 - mae: 5.7697
Epoch 3/10
1/1 [==============================] - 2s 2s/step - loss: 56.8146 - mae: 4.7450
Epoch 4/10
1/1 [====================

In [9]:
wmodel = Sequential([
    layers.LSTM(512, input_shape=(wtrain_inputs.shape[1],wtrain_inputs.shape[2]), return_sequences=True),
    layers.LSTM(128),
    layers.Dense(7, activation = 'relu')
])

wmodel.compile(loss='mse',optimizer='adam')
wmodel.summary()
wmodel.fit(wtrain_inputs, wtrain_labels,
    epochs=100
)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 1141, 512)         1069056   
                                                                 
 lstm_3 (LSTM)               (None, 128)               328192    
                                                                 
 dense_1 (Dense)             (None, 7)                 903       
                                                                 
Total params: 1,398,151
Trainable params: 1,398,151
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 6s 6s/step - loss: 71.4373
Epoch 2/100
1/1 [==============================] - 2s 2s/step - loss: 63.5891
Epoch 3/100
1/1 [==============================] - 2s 2s/step - loss: 56.1074
Epoch 4/100
1/1 [==============================] - 2s 2s/step - loss: 49.9

Epoch 95/100
1/1 [==============================] - 3s 3s/step - loss: 2.0663
Epoch 96/100
1/1 [==============================] - 3s 3s/step - loss: 1.9889
Epoch 97/100
1/1 [==============================] - 3s 3s/step - loss: 1.9138
Epoch 98/100
1/1 [==============================] - 3s 3s/step - loss: 1.8410
Epoch 99/100
1/1 [==============================] - 3s 3s/step - loss: 1.7707
Epoch 100/100
1/1 [==============================] - 3s 3s/step - loss: 1.7026


In [10]:
mmodel = Sequential([
    layers.LSTM(512, input_shape=(mtrain_inputs.shape[1],mtrain_inputs.shape[2]), return_sequences=True),
    layers.LSTM(256),
    layers.Dense(30, activation = 'relu')
])

mmodel.compile(loss='mse',optimizer='adam')
mmodel.summary()
mmodel.fit(mtrain_inputs, mtrain_labels,
    epochs=100
)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 1118, 512)         1069056   
                                                                 
 lstm_5 (LSTM)               (None, 256)               787456    
                                                                 
 dense_2 (Dense)             (None, 30)                7710      
                                                                 
Total params: 1,864,222
Trainable params: 1,864,222
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 12s 12s/step - loss: 65.6201
Epoch 2/100
1/1 [==============================] - 3s 3s/step - loss: 58.6608
Epoch 3/100
1/1 [==============================] - 3s 3s/step - loss: 52.7546
Epoch 4/100
1/1 [==============================] - 3s 3s/step - loss: 48

1/1 [==============================] - 3s 3s/step - loss: 4.5030
Epoch 96/100
1/1 [==============================] - 3s 3s/step - loss: 4.4957
Epoch 97/100
1/1 [==============================] - 3s 3s/step - loss: 4.4873
Epoch 98/100
1/1 [==============================] - 3s 3s/step - loss: 4.4817
Epoch 99/100
1/1 [==============================] - 3s 3s/step - loss: 4.4766
Epoch 100/100
1/1 [==============================] - 3s 3s/step - loss: 4.4716


In [13]:
a=[]
a.append(returnInputs(sa, sadata))
a = np.array(a)
a = a[:,:1141,:]
print(a)
wmodel.predict(a)

[[[ 5.26        2.310472   -0.14501075 ...  0.07745662 -0.58799426
    0.15273633]
  [ 5.09        1.6128305   0.06160386 ... -0.06111653  2.42368367
    0.13651005]
  [ 5.16        1.3905263   0.06160386 ... -0.06111653  2.42368367
    0.13651005]
  ...
  [ 5.95        0.7696187   0.42443926 ... -0.20876186  2.02212661
   -0.18861003]
  [ 5.86        0.9284761   0.42443926 ... -0.20876186  2.02212661
   -0.18861003]
  [ 5.8         1.0356971   0.42443926 ... -0.20876186  2.02212661
   -0.18861003]]]
1/1 [==============================] - 1s 538ms/step


array([[5.913666 , 5.860912 , 5.7413707, 5.812927 , 5.650694 , 5.60696  ,
        5.5205317]], dtype=float32)

In [14]:
dmodel.save('dailymodel.h5')
wmodel.save('weeklymodel.h5')
mmodel.save('monthlymodel.h5')